version: "3.9"

services:
  api:
    build: ./api
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
