apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: predictions-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "predictions"
        - name: POSTGRES_USER
          value: "fastapi_user"
        - name: POSTGRES_PASSWORD
          value: "supersecret"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: predictions-app
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
