apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: predictions-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: password
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        volumeMounts:
        - name: pgadmin-storage
          mountPath: /var/lib/pgadmin
        ports:
        - containerPort: 80
      volumes:
      - name: pgadmin-storage
        persistentVolumeClaim:
          claimName: pgadmin-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: predictions-app
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer